services:
  - type: web
    name: the-tikhi-ecommerce
    env: node
    buildCommand: "npm install && npm run db:deploy && npm run build"
    startCommand: "node dist/server.cjs"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
